name: MLOps CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Cloner le dépôt
      - uses: actions/checkout@v3

      # 2️⃣ Installer Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # 3️⃣ Installer les dépendances via Makefile
      - name: Install dependencies
        run: make install

      # 4️⃣ Lancer le lint via Makefile
      - name: Lint
        run: make lint

      # 5️⃣ Lancer les tests via Makefile
      - name: Test
        run: make test

